<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="BO\" />
    <Folder Include="BlApi\" />
	<ProjectReference Include="..\DalFacade\DalFacade.csproj"/>
    <ProjectReference Include="..\DalList\DalList.csproj"/>

  </ItemGroup>

</Project>
